---
version: "3.8"
services:
  lockbox_1:
    image: commerceblock/lockbox:replica
    networks:
      - default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "19001:8000"
    environment:
      SGX_MODE: SW
      SGX_SDK: /opt/intel/sgxsdk
      LD_LIBRARY_PATH: /opt/intel/sgxsdk/sdk_libs
      LOCKBOX_DB_PATH: /tmp/lockbox
      LOCKBOX_KEY_DB_PATH: /tmp/lockbox_key
      LOCKBOX_ENC_INDEX: 1
      LOCKBOX_URL_SRC: http://lockbox_0:8000
      LOCKBOX_URL_DST: http://lockbox_1:8000
    volumes:
      - ./data/lockbox_1:/tmp/lockbox
      - ./data/lockbox_key_1:/tmp/lockbox_key
    command: >
      bash -c "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/sgx-aesm-service/aesm/ /opt/intel/sgx-aesm-service/aesm/aesm_service;
                /opt/lockbox/bin/server_exec"