version: "3.8"
services:
  mercurydb:
    image: timescale/timescaledb:latest-pg12
    networks:
      - default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD: "password"
      TIMESCALEDB_TELEMETRY: "off"
    volumes:
      - ./data/mercurydb:/var/lib/postgresql/data
    ports:
      - "15432:5432"



  lockbox_1:
    image: commerceblock/lockbox:replica
    networks:
      - default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "19001:8000"
    environment:
      SGX_MODE: SW
      SGX_SDK: /opt/intel/sgxsdk
      LD_LIBRARY_PATH: /opt/intel/sgxsdk/sdk_libs
      LOCKBOX_DB_PATH: /tmp/lockbox
      LOCKBOX_KEY_DB_PATH: /tmp/lockbox_key
      LOCKBOX_ENC_INDEX: 1
      LOCKBOX_URL_SRC: http://lockbox_0:8000
      LOCKBOX_URL_DST: http://lockbox_1:8000
    volumes:
      - ./data/lockbox_1:/tmp/lockbox
      - ./data/lockbox_key_1:/tmp/lockbox_key
    command: >
      bash -c "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/sgx-aesm-service/aesm/ /opt/intel/sgx-aesm-service/aesm/aesm_service;
                /opt/lockbox/bin/server_exec"

  lockbox_0:
    image: commerceblock/lockbox:replica
    networks:
      - default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "19000:8000"
    environment:
      SGX_MODE: SW
      SGX_SDK: /opt/intel/sgxsdk
      LD_LIBRARY_PATH: /opt/intel/sgxsdk/sdk_libs
      LOCKBOX_DB_PATH: /tmp/lockbox
      LOCKBOX_KEY_DB_PATH: /tmp/lockbox_key
      LOCKBOX_ENC_INDEX: 0
      LOCKBOX_URL_SRC: http://lockbox_0:8000
      LOCKBOX_URL_DST: http://lockbox_1:8000
    volumes:
      - ./data/lockbox_0:/tmp/lockbox
      - ./data/lockbox_key_0:/tmp/lockbox_key
    command: >
      bash -c "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/sgx-aesm-service/aesm/ /opt/intel/sgx-aesm-service/aesm/aesm_service;
                /opt/lockbox/bin/server_exec"

  lockbox_init_shared:
    image: commerceblock/lockbox:replica
    depends_on:
      - lockbox_0
      - lockbox_1
    networks:
      - default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "19002:8000"
    environment:
      SGX_MODE: SW
      SGX_SDK: /opt/intel/sgxsdk
      LD_LIBRARY_PATH: /opt/intel/sgxsdk/sdk_libs
      LOCKBOX_ENC_INDEX: 0
      LOCKBOX_URL_SRC: http://lockbox_0:8000
      LOCKBOX_URL_DST: http://lockbox_1:8000
    command: >
      bash -c "/opt/lockbox/bin/init_shared_exec"
  
  mercury:
    image: commerceblock/mercury:latest
    environment:
      - MERC_DB_USER_W=postgres
      - MERC_DB_PASS_W=password
      - MERC_DB_HOST_W=sim_mercurydb
      - MERC_DB_PORT_W=5432
      - MERC_DB_DATABASE_W=postgres
      - MERC_DB_USER_R=postgres
      - MERC_DB_PASS_R=password
      - MERC_DB_HOST_R=sim_mercurydb
      - MERC_DB_PORT_R=5432
      - MERC_DB_DATABASE_R=postgres
      - MERC_NETWORK=regtest
      - MERC_BLOCK_TIME=2
      - MERC_LOCKBOX=http://lockbox_0:8000
      - RUST_LOG=debug
      - MERC_TESTING_MODE=false
      - MERC_REQUIRED_CONFIRMATION=0
      - MERC_PUNISHMENT_DURATION=3600
      - MERC_UTXO_TIMEOUT=60
      - MERC_BATCH_LIFETIME=3600
      - MERC_LOCKHEIGHT_INIT=10000
      - MERC_LH_DECREMENT=100
      - MERC_FEE_ADDRESS=bcrt1qy6jn9a2lgaumeedqxzq2s0497s5zr5645xmzuk
      - MERC_FEE_DEPOSIT=0
      - MERC_FEE_WITHDRAW=300
#      - MERC_MAINSTAY_CONFIG=""
      - MERC_WATCH_ONLY=false
#      - MERC_BITCOIND=""
    networks:
      - default
    ports:
      - "18000:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: server
      
  bitcoin:
    image: paulius6/bitcoin:0.20.0
    networks:
      - default
    volumes:
      - ./data/bitcoin:/home/bitcoin/.bitcoin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "18332:8332"
    command: >-
      bitcoind
        -printtoconsole
        -rpcuser=${BITCOIN_RPC_USER:-username}
        -rpcpassword=${BITCOIN_RPC_PASSWORD:-password}
        -rpcallowip=0.0.0.0/0
        -rpcbind=0.0.0.0
        -rpcport=8332
        -server=1
        -txindex=1
        -prune=0
        -regtest=1
        -fallbackfee=1
        -maxtxfee=1

networks:
  default:
    driver: overlay
    ipam:
      config:
      - subnet: 10.6.6.0/24
