version: "3.8"
services:
  mercurydb:
    image: timescale/timescaledb:latest-pg12
    networks:
      - default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD: "password"
      TIMESCALEDB_TELEMETRY: "off"
    volumes:
      - ./data/mercurydb:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  lockbox_0:
    image: lockbox:test_replica
    networks:
      - default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "19000:8000"
    environment:
      SGX_MODE: SW
      SGX_SDK: /opt/intel/sgxsdk
      LD_LIBRARY_PATH: /opt/intel/sgxsdk/sdk_libs
      LOCKBOX_DB_PATH: /tmp/lockbox
      LOCKBOX_ENC_INDEX: 0
      LOCKBOX_CLIENT_URL_SRC: lockbox_0 
      LOCKBOX_CLIENT_URL_DEST: lockbox_1
    volumes:
      - ./data/lockbox_0:/tmp/lockbox
    command: >
      bash -c "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/sgx-aesm-service/aesm/ /opt/intel/sgx-aesm-service/aesm/aesm_service;
                /opt/lockbox/bin/server_exec"

  
  mercury:
    image: commerceblock/mercury:latest
    environment:
      - MERC_DB_USER_W=postgres
      - MERC_DB_PASS_W=password
      - MERC_DB_HOST_W=sim_mercurydb
      - MERC_DB_PORT_W=5432
      - MERC_DB_DATABASE_W=postgres
      - MERC_DB_USER_R=postgres
      - MERC_DB_PASS_R=password
      - MERC_DB_HOST_R=sim_mercurydb
      - MERC_DB_PORT_R=5432
      - MERC_DB_DATABASE_R=postgres
      - MERC_NETWORK=regtest
      - MERC_BLOCK_TIME=2
      - MERC_LOCKBOX=lockbox_0
      - MERC_ELECTRUM_SERVER=tcp://electrumx_test:50001
      - RUST_LOG=debug
      - MERC_FEE_DEPOSIT=0
    networks:
      - default
    ports:
      - "18000:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: server
      
  bitcoin:
    image: paulius6/bitcoin:0.20.0
    networks:
      - default
    volumes:
      - ./data/bitcoin:/home/bitcoin/.bitcoin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "18332:8332"
    command: >-
      bitcoind
        -printtoconsole
        -rpcuser=${BITCOIN_RPC_USER:-username}
        -rpcpassword=${BITCOIN_RPC_PASSWORD:-password}
        -rpcallowip=0.0.0.0/0
        -rpcbind=0.0.0.0
        -rpcport=8332
        -server=1
        -txindex=1
        -prune=0
        -regtest=1
        -fallbackfee=1
        -maxtxfee=1

  electrumx_test:
    image: paulius6/electrumx
    environment:
      DB_DIRECTORY: /electrum-db
      DAEMON_URL: http://username:password@bitcoin:8332/
      SERVICES: tcp://:50001
      COIN: BitcoinSegwit
      NET: regtest
      MAX_SEND: 30000000
    ulimits:
      nofile:
        soft: 2500
        hard: 2500
    volumes:
      - ./data/electrumx-test:/electrum-db
    networks:
      - default
    ports:
      - "50001:50001"
    command: electrumx_server

networks:
  default:
    driver: overlay
    ipam:
      config:
      - subnet: 10.6.6.0/24
